### ISSUE TITLE
Emotes not sorting by streamer

### ISSUE THREAD

**Issue by matthewjk123** [cletusc/Userscript--Twitch-Chat-Emotes#75]
Hello. I am a Partnered Streamer on Twitch, and I have a sub button. Me and Night are friends and he did me the favor of adding two emotes into BTTV for me. These emotes for some reason are not showing under my section in your addon, they are showing in the "All Emotes" section, (screenshot: http://i.imgur.com/kbaP6Io.png). This is where they should be, (screenshot: http://i.imgur.com/6QkXijz.png). If you could look into this, that would be great. Also, I would like to let you know that all of the BTTV emotes are also in the "All Emotes" section, when they should have their own. 

Thanks, Matthewjk

**Comment by cletusc** [comment]
Emotes added by 3rd parties, e.g. BTTV, must have a channel specified for the emote in order for it to group. Although not documented formally, I linked @night to [some documentation when I added the API](https://github.com/cletusc/Userscript--Twitch-Chat-Emotes/issues/72#issuecomment-70398641).

As shown on [BTTV's emotes pulled from their server](https://api.betterttv.net/emotes), they aren't specifying the channel:

```javascript
{
    status : 200,
    emotes :
    [
        0 :
        {
            url : "//cdn.betterttv.net/emotes/trollface.png",
            width : 23,
            height : 19,
            regex : ":tf:"
            // NEED CHANNEL HERE!
        },
        // ...
    ]
}
```

Channel is also not added [in the method they use with my API](https://github.com/night/BetterTTV/blob/master/betterttv.js#L1163-L1191).

There is an issue that Night made me aware of, and that's a group showing up twice, but is not related to this.

Not my issue--closing.

**Comment by night** [comment]
While I added channel labels, this did not use to be an issue as the emotes contained emoticon_set. What changed to break that?

**Comment by cletusc** [comment]
I've never used the emoteset to sort, only to see if it can be used. There has always been a need for channel ever since I started grouping (many many versions ago). How an emote has been appended to the menu has been the same [since at least Oct 2014](https://github.com/cletusc/Userscript--Twitch-Chat-Emotes/commit/615ec60d86789ea635ff6e3a199d528b12ca0eb7#diff-4fa23f0e9c16e2b6fbf4d981baf0e655R575) and even then, I've always checked the channel. The only thing I need *now* is `emote.url`, `emote.channel`, and `emote.text`. If you don't provide `emote.channel`, it gets thrown in the globals section.

This behavior with how emotes are appended, and how they are parsed, is in the process of being reworked and documented fully, both to be more rugged, and to easier to understand code-wise. I'll be adding console warnings on things you *should* be adding, like `emote.channel`.
