### ISSUE TITLE
Remove background from certain non-transparent emotes

### ISSUE THREAD

**Issue by matt3541** [cletusc/Userscript--Twitch-Chat-Emotes#94]
This was fixed in chat by https://github.com/night/BetterTTV/issues/1087 but still needs to be fixed in the emote menu

**Comment by cletusc** [comment]
Closing as wontfix. This is something I'm not willing to override--I show _exactly_ what the emote is. If Twitch wants it with white background, it will remain with a white background.

See also #11

**Comment by matt3541** [comment]
But do you actually think Twitch wants them that way? Dark mode was not a native Twitch feature at the time of creating those emotes thus it was not a concern to Twitch whether or not they were transparent. There isn't even any work to be done, just swap them for the already fixed BTTV versions.

**Comment by cletusc** [comment]
I doubt Twitch wants them with white background. Twitch has a native dark mode _now_, so if they care about it, they would remove the white background themselves.

The goal is to have a solution that is low/no maintenance and manual overrides on a _per-emote-basis_ goes against that. If I fix the global emotes, then why shouldn't I also do sub emotes that clearly need to be fixed? That's why I'm choosing not to do either. Twitch can fix the globals, and channels can fix their own sub emotes.

**Comment by matt3541** [comment]
Understood, thanks

**Comment by cletusc** [comment]
As another solution you could suggest to BTTV: override it themselves in the menu if they aren't already. The menu loads the native emotes first, then it loads any third party emotes (like BTTV) and allows global emotes to be changed.
