### ISSUE TITLE
Console errors in BTTV

### ISSUE THREAD

**Issue by EhsanKia** [cletusc/Userscript--Twitch-Chat-Emotes#99]
The emote menu seems to be throwing some errors recently:

```
betterttv.js?0.6009572023012004:240 Uncaught TypeError: Cannot read property 'get' of null
    at https://cdn.betterttv.net/betterttv.js?0.6009572023012004:240:26470
    at Array.some (native)
    at Object.o.get (https://cdn.betterttv.net/betterttv.js?0.6009572023012004:240:26430)
    at n.onEmotesChange (https://cdn.betterttv.net/betterttv.js?0.6009572023012004:241:3838)
```

Seems to be around here:
https://github.com/cletusc/Userscript--Twitch-Chat-Emotes/blob/5fbf5076906840216590435146fc0a8034c3d3e6/src/modules/twitch-api.js#L77

Any chance you could look into it?

**Comment by sunnyphp** [comment]
Plugin not working now. They throw error in console and stops loading stream window (just blank window).
![sample](https://cloud.githubusercontent.com/assets/3903438/25348690/b6d9d0ec-2927-11e7-9647-f07facceb23a.png)

**Comment by cletusc** [comment]
Are you able to [turn on debugging](https://github.com/cletusc/Userscript--Twitch-Chat-Emotes#debugging), refresh, and post what it logs?

This may have already been fixed by [v2.1.4](https://github.com/cletusc/Userscript--Twitch-Chat-Emotes/releases/tag/v2.1.4) released a couple weeks ago; specifically, commit 40bb3eb5173c1a4ad9297c046f12e458cd2aa3cc should have fixed this, but please let me know what your debugging says and it should help confirm.

**Comment by sunnyphp** [comment]
Oh, sorry, I'm using version 1.1.4 :smile:

**Comment by cletusc** [comment]
Get with the times! 😆
